### PR TITLE
Add adapt = False (prior_scale=1) option to lfc_shrink()

### PR DESCRIPTION
**Pull request by awalsh17**
#### Reference Issue or PRs

This is in reference to #264 

#### What does your PR implement? Be specific.
This adds an option to lfc_shrink() to allow one to keep prior_scale = 1. 
This is equivalent to the R package implementation of DESeq2::lfcShrink( apeAdapt = FALSE )

I tested some and the behavior is similar to the R package. But not 100%. I am not sure, but likely a difference in the parameters I passed to each. 
These plots are from using the same data, contrast, and adapt = False argument.

image

### CODE REVIEW

**Comment by BorisMuzellec** [comment]
Thanks a lot for this PR @awalsh17! I'll try to add a test to automatically compare with deseq2 by the end of the week.

**Comment by BorisMuzellec** [comment]
> I tested some and the behavior is similar to the R package. But not 100%. I am not sure, but likely a difference in the parameters I passed to each. These plots are from using the same data, contrast, and adapt = False argument.

@awalsh17 in those plots did you run lfc shrinkage starting from the same size factors, dispersions and LFCs, or did you run a DESeq2 pipeline and a PyDESeq2 pipeline independently (starting from the same data)?

**Comment by awalsh17** [comment]
> > I tested some and the behavior is similar to the R package. But not 100%. I am not sure, but likely a difference in the parameters I passed to each. These plots are from using the same data, contrast, and adapt = False argument.
> 
> @awalsh17 in those plots did you run lfc shrinkage starting from the same size factors, dispersions and LFCs, or did you run a DESeq2 pipeline and a PyDESeq2 pipeline independently (starting from the same data)?

@BorisMuzellec Good point. I ran them completely independently (starting from the same data). I could repeat using the same data input to just the lfc shrinkage?

**Comment by BorisMuzellec** [comment]
> @BorisMuzellec Good point. I ran them completely independently (starting from the same data). I could repeat using the same data input to just the lfc shrinkage?

If you have time for it, a good sanity check would be to test on real data indeed, but for this we would need to factor out differences between DESeq2 and PyDESeq2 in terms of dispersions by manually setting the same dispersions in both packages.

Otherwise, I think that the PR passing tests on the synthetic test data is good enough

**Review by BorisMuzellec — APPROVED** [review]

**Pull request merged**
